### PR TITLE
feat : add button and badge

### PR DESCRIPTION
**Pull request by ArjunJunna**
have added button and badge components

### CODE REVIEW

**Review by partha8 — COMMENTED** [review]
Hey, for the images in the avatar, try using object-fit: cover because right now it looks a little off and it can be easily corrected. Rest everything looks good.

**Review by Developers-codz — CHANGES_REQUESTED** [review]
Everything is looking good just an observation, Your outline button is not outline ?

**Review by partha8 — APPROVED** [review]
Yup, the changes the look good. Great work, keep it up!

**Comment by ArjunJunna** [comment]
> Everything is looking good just an observation, Your outline button is not outline ?

fixed it thanks

**Review by Developers-codz — APPROVED** [review]
Yeah, now its looking good.

**Comment by ArjunJunna** [comment]
> Yup, the changes the look good. Great work, keep it up!

Thank you

**Pull request merged**
